name: next_bus
description: "Next Bus"

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.11
  excel: ^2.0.6
  path_provider: ^2.0.12
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  flutter_native_splash: ^2.0.3

flutter_native_splash:
  color: "#ffffff"  # Background color for the splash screen
  image: "assets/logo.png"  # Path to your logo image
  android: true  # Enable for Android
  ios: true  # Enable for iOS


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/ktm_ekm_ksrtc.xlsx
    - assets/Logo1.png


